### ISSUE TITLE
Generating Recipe Dataset

### ISSUE THREAD

**Issue by ajemerson** [ajemerson/Recipe-Recommendation-System#2]
Scrape the Allrecipes website to generate dataset. Each recipe is a row. All ingredients are the columns. 2 columns for the food type (specific and general category).
Aditya - Dessets & Dinner
Andrew - Breakfast & Brunch & Lunch

**Comment by aditya-upadhyay** [comment]
https://developer.yummly.com/
I was considering this source also, just in case. Can you also take a look?

**Comment by ajemerson** [comment]
Yes, this looks like a fantastic resource. I found another project that analyzes this site's data:
https://github.com/alialamiidrissi/ADA_Course_Project
https://alioben.github.io/yummly/
If we can't derive enough patterns from the allrecipe source, let's use yummly.

**Comment by ajemerson** [comment]
The code for this is just about complete. The remaining tasks are:
- Scrape up to the last page for each category (possibly only even the last page depending on how the pages are structured)
- Ensure the ingredient list is itself not a string

@aditya-upadhyay

**Comment by ajemerson** [comment]
Closed by f107046b2f1642f9691cfe452a309e4364b4fcb7
