### ISSUE TITLE
Unit Conversion: Testing

### ISSUE THREAD

**Issue by npool9** [ajemerson/Recipe-Recommendation-System#4]
In UnitConversion.ipynb, I've done some preliminary testing to make sure conversions are calculated correctly and units are correctly accounted for. Please feel free to test this more based on what your web scraping finds!

**Comment by npool9** [comment]
I think recipe_parser.ipynb is ready for final testing. There are some things that we'll probably have to fix manually after creating the final dataset just because the formats of recipes aren't totally constant. But other than that, this seems to be working pretty well. Feel free to check it out with your own set of recipes! If you have any questions about running it, let me know.

**Comment by ajemerson** [comment]
Closed by 2ab34cc33dc8c06eb20b179016ad2a38887ca2d3
